#!/usr/bin/env bash

# usage:
# p2o --help
# p2o ./path/to/collection.json -f ./path/to/results.yml
echo docker run -t --rm=true -v $(pwd):/working -w /working postman-to-openapi $@
docker run -t --rm=true -v $(pwd):/working -w /working postman-to-openapi $@
